name: create gitbook source

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gitbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: build image for gitbook instruction
        run: |
          docker build . -t gitbook-server:latest
      
      - name: create container volume folder
        run: |
          mkdir -p gitbook
          mv README.md gitbook/SUMMARY.md
          mv README.md gitbook/README.md
          bash mv_folder.sh

      - name: install gitbook-plugins
        run: |
          docker run --rm -v "$PWD/gitbook:/gitbook" gitbook-server gitbook install

      - name: compile books
        run: |
          docker run --rm -v "$PWD/gitbook:/gitbook" gitbook-server gitbook build

      - name: push _book to branch gitbook_source
        env:
          TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          REF: github.com/${{github.repository}}
          MYEMAIL: talon6605@gmail.com
          MYNAME: Fail-Man
        run: |
          cd gitbook
          sudo chmod 777 -R _book
          cd _book
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git add . 
          git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
          git branch -M main
          git push --force --quiet "https://${TOKEN}@${REF}" main:gitbook_source